nom = input("Quel est votre nom ? ")
prenom = input("Quel est votre prénom ? ")
age = input("Quel est votre âge ? ")
ville = input("Dans quelle ville habitez-vous ? ")
print("Formulaire Etudiant :")
print("Nom : " + nom)
print("Prénom : " + prenom)
print("Âge : " + age)
print("Ville : " + ville)
